export const sample_hairs: any[] = [
    {
      id: '1',
      name: 'Pizza Pepperoni',
      price: 40,
      favorite: false,
      origins: ['italy'],
      stars: 4.5,
      imageUrl: 'assets/img/hair/1.jpg',
      tags: ['FastFood', 'Pizza', 'Lunch'],
      
    },
    {
      id: '2',
      name: 'Meatball',
      price: 20,
      favorite: true,
      origins: ['persia', 'middle east', 'china'],
      stars: 4.7,
      imageUrl: 'assets/img/hair/2.jpg',
      tags: ['SlowFood', 'Lunch'],
    },
    {
      id: '3',
      name: 'Hamburger',
      price: 50,
      favorite: false,
      origins: ['germany', 'us'],
      stars: 3.5,
      imageUrl: 'assets/img/hair/3.jpg',
      tags: ['FastFood', 'Hamburger'],
    },
    {
      id: '4',
      name: 'Fried Potatoes',
      price: 200,
      favorite: true,
      origins: ['belgium', 'france'],
      stars: 3.3,
      imageUrl: 'assets/img/hair/4.webp',
      tags: ['FastFood', 'Fry'],
    },
    {
      id: '5',
      name: 'Chicken Soup',
      price: 30,
      favorite: false,
      origins: ['india', 'asia'],
      stars: 3.0,
      imageUrl: 'assets/img/hair/5.jpg',
      tags: ['SlowFood', 'Soup'],
    },
    {
      id: '6',
      name: 'Vegetables Pizza',
      price: 20,
      favorite: false,
      origins: ['italy'],
      stars: 4.0,
      imageUrl: 'assets/img/hair/6.jpg',
      tags: ['FastFood', 'Pizza', 'Lunch'],
    },
  ];
  
  export const sample_tags: any[] = [
    { name: 'All', count: 6 },
    { name: 'FastFood', count: 4 },
    { name: 'Pizza', count: 2 },
    { name: 'Lunch', count: 3 },
    { name: 'SlowFood', count: 2 },
    { name: 'Hamburger', count: 1 },
    { name: 'Fry', count: 1 },
    { name: 'Soup', count: 1 },
  ];
  
  export const sample_users: any[] = [
    {
      name: 'Fildi Hellen',
      email: 'intysilva1@gmail.com',
      password: '12345',
      address: 'Rabat',
      isAdmin: true,
    },
    {
      name: 'Naomi',
      email: 'Naomi@gmail.com',
      password: '12345',
      address: 'Kampala',
      isAdmin: false,
    },
  ];