export const sample_cosmetics: any[] = [
    {
      id: '1',
      name: 'Maybelline',
      price: 10,
      favorite: false,
      origins: ['italy'],
      stars: 4.5,
      imageUrl: 'assets/img/cosmetics/1.jpg',
      tags: ['Lipstick', 'gloss'],
    },
    {
      id: '1',
      name: 'Mac',
      price: 30,
      favorite: false,
      origins: ['italy'],
      stars: 4.5,
      imageUrl: 'assets/img/cosmetics/2.jpg',
      tags: ['Fondation', 'shades'],
    },
    {
      id: '3',
      name: 'Mac',
      price: 10,
      favorite: false,
      origins: ['italy'],
      stars: 4.5,
      imageUrl: 'assets/img/cosmetics/3.jpg',
      tags: ['Powder', 'Set'],
    },
    {
      id: '4',
      name: 'MakeUP Brushes',
      price: 20,
      favorite: false,
      origins: ['France'],
      stars: 4.5,
      imageUrl: 'assets/img/cosmetics/4.jpg',
      tags: ['Brushes'],
    },
    {
      id: '5',
      name: 'Elf',
      price: 10,
      favorite: false,
      origins: ['USA'],
      stars: 4.5,
      imageUrl: 'assets/img/cosmetics/5.webp',
      tags: ['Primer'],
    },
    {
      id: '6',
      name: 'Gloss',
      price: 15,
      favorite: false,
      origins: ['China'],
      stars: 4.5,
      imageUrl: 'assets/img/cosmetics/6.webp',
      tags: ['Lipstick','LipGloss'],
    },
  ];
  
  export const sample_tags: any[] = [
    { name: 'All', count: 6 },
    { name: 'Foundation', count: 1},
    { name: 'Primer', count: 1 },
    { name: 'Lipstick', count: 2 },
    { name: 'LipGloss', count: 1 },
    { name: 'Brushes', count: 1 },
    { name: 'Powder', count: 1 },
    { name: 'Set', count: 1 },
    { name: 'Shades', count: 1 },
  ];
  
  export const sample_users: any[] = [
    {
      name: 'Fildi Hellen',
      email: 'intysilva1@gmail.com',
      password: '12345',
      address: 'Rabat',
      isAdmin: true,
    },
    {
      name: 'Naomi',
      email: 'Naomi@gmail.com',
      password: '12345',
      address: 'Kampala',
      isAdmin: false,
    },
  ];