export const sample_foods: any[] = [
  {
    id: '1',
    name: 'Burger',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'assets/img/food/burger.jpg ',
    tags: ['FastFood', 'Burger', 'Lunch'],
  },
  {
    id: '2',
    name: 'Full Meal',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: 'assets/img/food/magic-foods.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '3',
    name: 'Sudanese Food',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['Sudan', 'Egypt'],
    stars: 3.5,
    imageUrl: 'assets/img/food/fool.jpg',
    tags: ['FastFood', 'WholeMeal','Lunch'],
  },
  {
    id: '4',
    name: 'Fried & Salades',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france','USA'],
    stars: 3.3,
    imageUrl: 'assets/img/food/meal1.jpg',
    tags: ['FastFood', 'Fry','salades','Burger'],
  },
  {
    id: '5',
    name: 'Fried Meat',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia','Africa'],
    stars: 3.0,
    imageUrl: 'assets/img/food/meat.webp',
    tags: ['SlowFood', 'Meat'],
  },
  {
    id: '6',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/img/food/pizza1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '7',
    name: ' Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/img/food/pizza.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '8',
    name: 'WholeMeal',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/img/food/menu.webp',
    tags: ['FastFood', 'spaghetti', 'Lunch'],
  },
  {
    id: '9',
    name: 'Local Food',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['Sudanese','Egypt','African'],
    stars: 4.0,
    imageUrl: 'assets/img/food/Molokhia.jpg',
    tags: ['WholeMeal', 'Dinner', 'Lunch'],
  },
];

export const sample_tags: any[] = [
  { name: 'All', count: 9 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Burger', count: 1 },
  { name: 'Dinner', count: 1 },
  { name: 'WholeMeal', count: 2 },
  { name: 'Meat', count: 1 },
  { name: 'LocalFood', count: 1 },
  { name: 'Fry', count: 1 },
];

export const sample_users: any[] = [
  {
    name: 'Fildi Hellen',
    email: 'intysilva1@gmail.com',
    password: '12345',
    address: 'Rabat',
    isAdmin: true,
  },
  {
    name: 'Naomi',
    email: 'Naomi@gmail.com',
    password: '12345',
    address: 'Kampala',
    isAdmin: false,
  },
];